import { defineStore } from "pinia"

export const useProjects = defineStore('projects', () => {
  const projects = [
    { id: 1, name: 'Опоры трубопроводов', projecttype: 'Вид продукции', projectname: 'Опоры трубопроводов', volume: 'Объем', quantity: '850 тонн', year: 'Год', yeardata: '2022', enduser: 'Конечный потребитель', endusername: ' Иркутский завод полимеров', img: '/img/izp.webp' },
    { id: 2, name: 'Опоры по чертежам заказчика', projecttype: 'Вид продукции', projectname: 'Опоры газохода', volume: 'Объем', quantity: '7 тонн', year: 'Год', yeardata: '2022', enduser: 'Конечный потребитель', endusername: 'ООО "ОЗНО"', img: '/img/opt1.webp' },
    { id: 3, name: 'Опоры разгрузочные', projecttype: 'Вид продукции', projectname: 'Опора ОР по ТУ 25.11.23-011-73847543-2020', volume: 'Объем', quantity: 'Три образца', year: 'Год', yeardata: '2021', enduser: 'Конечный потребитель', endusername: 'ПАО Газпром', img: '/img/opt2.webp' },
    { id: 4, name: 'Тестовые образцы для ПАО Газпром', projecttype: 'Вид продукции', projectname: 'Опоры ОСП 1420', volume: 'Объем', quantity: '2 тонны', year: 'Год', yeardata: '2021', enduser: 'Конечный потребитель', endusername: 'ПАО Газпром', img:'/img/opt3.webp'},
    { id: 5, name: 'Опоры неподвижные в в ППУ изоляции', projecttype: 'Вид продукции', projectname: 'Опоры типа 5-А для надземной прокладки с устройством электрообогрева', volume: 'Объем', quantity: '12 тонн, 70 штук', year: 'Год', yeardata: '2021', enduser: 'Конечный потребитель', endusername: 'Строительная компания', img:'/img/opt4.webp'},
    { id: 6, name: 'Мачта прожекторная', projecttype: 'Вид продукции', projectname: 'Мачта прожекторная H=35м', volume: 'Объем', quantity: '196 тонн', year: 'Год', yeardata: '2020', enduser: 'Конечный потребитель', endusername: 'ПАО НК Росснефть', img:'/img/opt5.webp'},
    { id: 7, name: 'Опоры КХ ИНК 18 тонн', projecttype: 'Вид продукции', projectname: 'Опоры КХ, ОПХ, ОПХ2', volume: 'Объем', quantity: '18 тонн', year: 'Год', yeardata: '2020', enduser: 'Конечный потребитель', endusername: 'Иркутская нефтяная компания', img:'/img/opt6.webp'},
    { id: 8, name: 'Опоры регулируемые', projecttype: 'Вид продукции', projectname: 'Опоры регулируемые', volume: 'Объем', quantity: '65 тонн', year: 'Год', yeardata: '2020', enduser: 'Конечный потребитель', endusername: 'ПАО Газпром', img:'/img/opt7.webp'},
    {id: 9, name:'Серийные опоры', projecttype:'Вид продукции', projectname:'Серийные опоры', volume:'Объем', quantity:'43 тонны', year:'Год', yeardata:'2020',enduser:'Конечный потребитель', endusername:'Иркутская нефтяная компания', img:'/img/opt8.webp'},
    {id: 10, name:'Ростверки для прожекторных мачт', projecttype:'Вид продукции', projectname:'Ростверки для прожекторных мачт', volume:'Объем', quantity:'20 тонн', year:'Год', yeardata:'2020',enduser:'Конечный потребитель', endusername:'ПАО АНК Башнефть', img:'/img/opt9.webp'},
    {id: 11, name:'Опоры ОСП', projecttype:'Вид продукции', projectname:'Опоры ОСП', volume:'Объем', quantity:'43 тонны', year:'Год', yeardata:'2020',enduser:'Конечный потребитель', endusername:'ПАО НК Росснефть', img:'/img/opt10.webp'},
    {id: 12, name:'Опоры ОППС', projecttype:'Вид продукции', projectname:'Опоры ОППС', volume:'Объем', quantity:'113 тонн', year:'Год', yeardata:'2020',enduser:'Конечный потребитель', endusername:'ПАО АНК Башнефть', img:'/img/opt11.webp'},
    {id: 13, name:'Каркас блок-бокса для медицинских работников', projecttype:'Вид продукции', projectname:'Каркас блок-бокса для медицинских работников', volume:'Объем', quantity:'22 штуки', year:'Год', yeardata:'2019',enduser:'Конечный потребитель', endusername:'Администрация Челябинской области', img:'/img/opt12.webp'},
    {id: 14, name:'Опоры ОПХ', projecttype:'Вид продукции', projectname:'Серийные опоры', volume:'Объем', quantity:'13 тонн', year:'Год', yeardata:'2019',enduser:'Конечный потребитель', endusername:'Иркутская нефтяная компания', img:'/img/opt13.webp'},
    {id: 15, name:'Опоры ОСП, ОПП', projecttype:'Вид продукции', projectname:'Опоры ОСП, ОПП', volume:'Объем', quantity:'98 тонн', year:'Год', yeardata:'2019',enduser:'Конечный потребитель', endusername:'ПАО НК Росснефть', img:'/img/opt14.webp'},
    {id: 16, name:'Серийные опоры', projecttype:'Вид продукции', projectname:'Серийные опоры', volume:'Объем', quantity:'20 тонн', year:'Год', yeardata:'2019',enduser:'Конечный потребитель', endusername:'Иркутская нефтяная компания', img:'/img/opt15.webp'},
    {id: 17, name:'Опоры ОН в ППУ изоляции', projecttype:'Вид продукции', projectname:'Опоры ОН в ППУ изоляции', volume:'Объем', quantity:'60 тонн', year:'Год', yeardata:'2019',enduser:'Конечный потребитель', endusername:'ПАО АНК Башнефть', img:'/img/opt16.webp'},
    {id: 18, name:'Опоры ОН в ППУ изоляции', projecttype:'Вид продукции', projectname:'Опоры ОН в ППУ изоляции', volume:'Объем', quantity:'10 тонн', year:'Год', yeardata:'2018',enduser:'Конечный потребитель', endusername:'ПАО АНК Башнефть', img:'/img/opt17.webp'},
    {id: 19, name:'ОСП 1020', projecttype:'Вид продукции', projectname:'ОСП 1020', volume:'Объем', quantity:'237 тонн', year:'Год', yeardata:'2017',enduser:'Конечный потребитель', endusername:'ПАО Лукойл', img:'/img/opt18.webp'},
    {id: 20, name:'Опоры ОБК100.720', projecttype:'Вид продукции', projectname:'Опоры ОБК100.720', volume:'Объем', quantity:'132 штук, 15 тонн.', year:'Год', yeardata:'2017',enduser:'Конечный потребитель', endusername:'ПАО Лукойл', img:'/img/opt19.webp'}, 
  ]
  return { projects }
})